# This file is part of the tschm/.config-templates repository
# (https://github.com/tschm/.config-templates).
#
# Workflow: Deptry
# Purpose: This workflow identifies missing and obsolete dependencies in the project.
#          It helps maintain a clean dependency tree by detecting unused packages and
#          implicit dependencies that should be explicitly declared.
name: "DEPTRY"

# Trigger: This workflow runs on every push and on pull requests to the main branch
on:
  push:
  pull_request:
    # Only run on pull requests targeting the main branch
    branches: [ main ]

# Permissions: Only read access to repository contents is needed
permissions:
    contents: read

jobs:
  # Job: Dependencies
  # Purpose: Checks the project's dependency health using deptry
  Analysis:
    if: github.repository != 'tschm/.config-templates'
    runs-on: ubuntu-latest
    #needs: parse-env

    steps:
      - name: Run deptry
        run: |
          make deptry

        #if: hashFiles('pyproject.toml') != ''
        #uses: tschm/cradle/actions/deptry@v0.3.06
        #with:
        #  source-folder: ${{ needs.parse-env.outputs.source-folder }}
