# This workflow builds and deploys marimo notebooks to GitHub Pages
# It runs automatically when changes are pushed to the main branch or can be triggered manually

name: MAINTENANCE

# Defines when the workflow will run
on:
  push

permissions:
  contents: 'read'

jobs:
  test-notebooks:
    uses: jebel-quant/marimushka/.github/workflows/test.yml@v0.1.4
    with:
      notebook-dir: notebooks
