# This workflow is responsible for bumping the version and publishing a new release
# It creates a new tag based on the repository's commit history

name: Bump version and publish

on:
  # This workflow is triggered manually via the GitHub UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

jobs:
  tagging:
    # The job requires write permissions to repository contents to create tags
    permissions:
      contents: write

    # The job runs on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

      - name: Create GitHub release with artifacts
        uses: softprops/action-gh-release@v2.3.2  # Third-party release action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
          tag_name: ${{ inputs.tag }}        # Use the provided tag
          generate_release_notes: true       # Automatically generate notes from commits

  # Job to build Marimo interactive notebooks and export them to HTML
  # This converts Python files in the notebooks directory
  # to interactive web pages
  # The build job exports marimo notebooks to static HTML/WebAssembly
  # into the folder artifacts/marimushka
  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    permissions:
      contents: read
    steps:
      - uses: jebel-quant/marimushka/@v0.1.4
        with:
          notebooks_wasm: notebooks
          notebooks: ''
          apps: notebooks

  # Job to combine all artifacts and prepare them for deployment
  # This job runs after the marimo job has completed
  build:
    permissions:
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin
    runs-on: ubuntu-latest
    needs:
      - marimo
      - tagging
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publish book    # specify the path to avoid direct exposure of marimushka
        id: deployment
        uses: tschm/cradle/actions/book@v0.3.06
        with:
          title: "Monkeys"
          links: |
            {
              "Notebooks": "./marimushka/index.html"
            }
